### ISSUE TITLE
Subtle Monte Carlo grain growth memory error

### ISSUE THREAD

**Issue by tkphd** [mesoscale/mmsp#21]
In Debian 7 (Wheezy) using GCC v. 4.7.2 with optimization level 2 or 3 (-O2, -O3) in serial (```g++```) or parallel (```mpic++```), both of
- ```examples/coarsening/grain_growth/anisotropic/Monte_Carlo``` and
- ```examples/coarsening/grain_growth/isotropic/Monte_Carlo```
hang in the first iteration of update(). The program executes successfully with lower optimization (-g, -O0, -O1), with different compiler versions (more recent GCC or with ICC v. 15.0.3), and in different operating systems (Debian Sid, Raspbian Jessie, Ubuntu Trusty).

It is possible, but extremely unlikely that this is a compiler bug. It's more likely a subtle memory error in either ```update()``` or ```ghostswap(grid,sublattice)```.

@fakemusleman, have you seen intermittent bugs with this code elsewhere? Any suggestions for places to look? I'll keep poking around with a debugger, but with limited familiarity with the algorithm, I'm not sure how far I'll get.

**Comment by tkphd** [comment]
Bug was un-initialized memory in C-style integer arrays. Replaced with vectors explicitly initialized:

```vector<int> safe_array(dim,0);``` instead of ```int unsafe_array[dim];```.

Fixed in unit_test_dev branch, commit 8006afad8c: coming soon.

**Comment by fakemusleman** [comment]
Thanks for the catch.
 I was intend to write Int unsafe_array[dim] = {0}; but I forgot the second half of the line.

Thanks for the effort, Trevor

Have a nice weekend !

Yixuan

**Comment by tkphd** [comment]
Yep, that would have worked, too. Thanks!
