### ISSUE TITLE
Templated update function confusing in examples?

### ISSUE THREAD

**Issue by lucentdan** [mesoscale/mmsp#41]
I wonder if we should avoid using only templated functions in examples?  I wonder if less general example in (for example) the isotropic phase field grain growth directory would be more helpful to users?

I agree that the templated code permits the three tests to run appropriately.

Just wanted to have a couple of exchanges on this topic.

**Comment by tkphd** [comment]
If we ultimately want to implement the examples without templated functions, we would have to instantiate each ```generate``` and ```update``` function for 1-, 2-, and 3-dimensions and as many fundamental datatypes (```float```, ```double```) as are likely to arise. This is certainly possible, simply revert some of the changes in 80b291d. But I made those changes for good reasons in the first place: I personally found the original versions (with multiple duplicate functions for no apparently good reason) less helpful, more tedious to read, and much harder to repurpose for experimental use. My feeling is that the code should be written in as general a form as possible, to make remixing and reuse easy and broadly possible. If templates are confusing, we can write a chapter in the documentation about what they're about, why we use them, and further reading for neophytes and non-believers.

Have I missed some compelling reason to avoid templating?

**Comment by lucentdan** [comment]
You have not missed something.  Your idea of a chapter on the templating and maybe some words on the templating philosophy would be most helpful.  I can take a crack at those.  Thanks for the comment, sir!
