### ISSUE TITLE
mmsp2png fails to compile

### ISSUE THREAD

**Issue by amjokisaari** [mesoscale/mmsp#44]
Currently installing MMSP (git cloned; Ubuntu Linux 16.04) following the manual, but running into the following problem: 

[amj][~/projects/mmsp/utility]> make
g++ -O2 -Wall -I ../include/ mmsp2vti.cpp -o mmsp2vti -lz
g++ -O2 -Wall -I ../include/ mmsp2pvd.cpp -o mmsp2pvd -lz
g++ -O2 -Wall -I ../include/ mmsp2png.cpp -o mmsp2png -lz -lpng
mmsp2png.cpp:13:16: fatal error: png.h: No such file or directory
compilation terminated.
Makefile:25: recipe for target 'mmsp2png' failed
make: *** [mmsp2png] Error 1

I believe I'm missing a particular library, but would prefer you to specify before I hunt for the dependency myself.

**Comment by tkphd** [comment]
Right you are. The missing header comes from libpng. In Debian-flavored distros, please
```
apt-get install libpng12-dev
```
I will update the dependencies list with this info, and try tracking down the packages for other distros.

**Comment by amjokisaari** [comment]
Ok, that worked, thanks.  Just so you know, my compiler (gcc 5.3.0) is throwing a ton of warnings on a lot of those utilities that come after mmsp2png in the makefile.

**Comment by tkphd** [comment]
Interesting. Can you paste a snippet of the warnings?

**Comment by amjokisaari** [comment]
There are a lot... some are warnings about "i" being undeclared, such as:

In file included from ../include/MMSP.hpp:9:0,
                 from mmsp2png.cpp:15:
../include/MMSP.sparse.hpp: In function ‘void convert_sparses(const MMSP::grid<dim, MMSP::sparse<U> >&, const int&, int, int, const double&, const double&, bool, const std::set<double>&, const int&, const double&, const std::set<int>&, const unsigned int&, unsigned char*) [with int dim = 1; T = long double]’:
../include/MMSP.sparse.hpp:126:14: warning: ‘i’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   return data[i].index;
              ^
mmsp2png.cpp:1128:9: note: ‘i’ was declared here
     int i=GRID(n).index(i);

Others include warnings about logicals: 

sPF2PF.cpp:82:31: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
  if (not dim == 1 and not dim == 2 and not dim == 3) {
                               ^
sPF2PF.cpp:82:31: warning: comparison of constant ‘2’ with boolean expression is always false [-Wbool-compare]

**Comment by tkphd** [comment]
Cool, that mmsp2png error is significant. My compiler (gcc 4.9) is much less picky.
I switched the default branch from master to develop, which fixes some issues and creates others. Could I trouble you to check out develop (git checkout -b develop && git pull origin develop), record the full output from your compiler, and e-mail it to me? Please?

**Comment by amjokisaari** [comment]
Sure, will do after lunch.

**Comment by amjokisaari** [comment]
Do you want this output with the color codes, or not?

**Comment by tkphd** [comment]
Not sure what you're asking... Plain text is fine.

**Comment by amjokisaari** [comment]
If I use the script command to output all of the terminal information into a log file, it includes a ton of color codes, for example: 

Script started on Wed 09 Aug 2017 01:08:03 PM CDT
^[[1;34m[amj]^[[1;32m[~/projects/mmsp/utility]^[[0m> ls

irritating if you look at it in a text editor; color codes properly if you cat it to a terminal.  

Copypasta it is for plain text!
