### ISSUE TITLE
build_examples.sh in mmsp/test fails

### ISSUE THREAD

**Issue by amjokisaari** [mesoscale/mmsp#47]
Happens in develop and master branches, it looks like the serial versions of the examples  build, but parallel build fails.  Here is output for the first test that tries to build:

[amj][~/projects/mmsp/test]> ./build_examples.sh 
Building examples in serial and parallel, 2-dimensional, taking 1000 steps, using 4/8 MPI ranks
mmsp2png utility not found. Please check your installation, or pass --noviz.
---------------------------------------------------------------------------
 1/25 beginners_diffusion/                                        0 seconds
      example does not match generic pattern for execution
 2/25 coarsening/grain_growth/anisotropic/Monte_Carlo/          /tmp/ccYRAxVP.o: In function `void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) [clone .isra.60]':
graingrowth.cpp:(.text+0xab): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/tmp/ccYRAxVP.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*)':
graingrowth.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EERKS8_PKS5_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EERKS8_PKS5_]+0x48): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
/tmp/ccYRAxVP.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > MMSP::name<3, int>(MMSP::grid<3, int> const&)':
graingrowth.cpp:(.text._ZN4MMSP4nameILi3EiEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_4gridIXT_ET0_EE[_ZN4MMSP4nameILi3EiEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_4gridIXT_ET0_EE]+0x6d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
/tmp/ccYRAxVP.o: In function `_GLOBAL__sub_I__ZN4MMSP4nameB5cxx11ERKb':
graingrowth.cpp:(.text.startup+0x3c): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
graingrowth.cpp:(.text.startup+0x5f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/tmp/ccYRAxVP.o: In function `main':
graingrowth.cpp:(.text.startup+0x1c5): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x232): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)'
graingrowth.cpp:(.text.startup+0x2c5): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)'
graingrowth.cpp:(.text.startup+0x310): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x340): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)'
graingrowth.cpp:(.text.startup+0x36b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x41a): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)'
graingrowth.cpp:(.text.startup+0x436): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x448): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const'
graingrowth.cpp:(.text.startup+0x4a1): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x4bc): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x4dd): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x4f7): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x50b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x571): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x589): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x5ab): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x5c3): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const'
graingrowth.cpp:(.text.startup+0x5e1): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x63e): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x655): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x68a): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
graingrowth.cpp:(.text.startup+0x6fd): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x71b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x72f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x73f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
graingrowth.cpp:(.text.startup+0x772): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
graingrowth.cpp:(.text.startup+0x790): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text.startup+0x7bf): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text.startup+0x940): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
graingrowth.cpp:(.text.startup+0x959): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text.startup+0x9dd): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
graingrowth.cpp:(.text.startup+0xa0b): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)'
graingrowth.cpp:(.text.startup+0xaac): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text.startup+0xb1c): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text.startup+0xb4a): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text.startup+0xb85): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text.startup+0xbcc): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text.startup+0xcf6): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
graingrowth.cpp:(.text.startup+0xd0f): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text.startup+0xd95): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
graingrowth.cpp:(.text.startup+0xdc3): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)'
graingrowth.cpp:(.text.startup+0xe64): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text.startup+0xecc): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text.startup+0xefc): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text.startup+0xf35): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text.startup+0xf7c): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text.startup+0x1005): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
graingrowth.cpp:(.text.startup+0x101e): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text.startup+0x10a5): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
graingrowth.cpp:(.text.startup+0x10d3): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)'
graingrowth.cpp:(.text.startup+0x1174): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text.startup+0x11dc): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text.startup+0x120c): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text.startup+0x1245): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text.startup+0x128c): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text.startup+0x12a6): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text.startup+0x1349): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x1361): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x1378): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x13a7): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
graingrowth.cpp:(.text.startup+0x1431): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x1448): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x1477): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
graingrowth.cpp:(.text.startup+0x15b3): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x1738): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)'
graingrowth.cpp:(.text.startup+0x1763): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const'
graingrowth.cpp:(.text.startup+0x17da): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const'
/tmp/ccYRAxVP.o: In function `MMSP::grid<1, int>::input(char const*, int, int)':
graingrowth.cpp:(.text._ZN4MMSP4gridILi1EiE5inputEPKcii[_ZN4MMSP4gridILi1EiE5inputEPKcii]+0x5f): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)'
/tmp/ccYRAxVP.o: In function `MMSP::grid<2, int>::input(char const*, int, int)':
graingrowth.cpp:(.text._ZN4MMSP4gridILi2EiE5inputEPKcii[_ZN4MMSP4gridILi2EiE5inputEPKcii]+0x5f): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)'
/tmp/ccYRAxVP.o: In function `MMSP::grid<2, int>::output(char const*) const':
graingrowth.cpp:(.text._ZNK4MMSP4gridILi2EiE6outputEPKc[_ZNK4MMSP4gridILi2EiE6outputEPKc]+0x12f): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi2EiE6outputEPKc[_ZNK4MMSP4gridILi2EiE6outputEPKc]+0x2d0): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi2EiE6outputEPKc[_ZNK4MMSP4gridILi2EiE6outputEPKc]+0x336): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi2EiE6outputEPKc[_ZNK4MMSP4gridILi2EiE6outputEPKc]+0x38d): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi2EiE6outputEPKc[_ZNK4MMSP4gridILi2EiE6outputEPKc]+0x413): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi2EiE6outputEPKc[_ZNK4MMSP4gridILi2EiE6outputEPKc]+0x5de): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi2EiE6outputEPKc[_ZNK4MMSP4gridILi2EiE6outputEPKc]+0x65c): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi2EiE6outputEPKc[_ZNK4MMSP4gridILi2EiE6outputEPKc]+0x714): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi2EiE6outputEPKc[_ZNK4MMSP4gridILi2EiE6outputEPKc]+0x161d): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi2EiE6outputEPKc[_ZNK4MMSP4gridILi2EiE6outputEPKc]+0x16fd): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
/tmp/ccYRAxVP.o: In function `MMSP::grid<1, int>::output(char const*) const':
graingrowth.cpp:(.text._ZNK4MMSP4gridILi1EiE6outputEPKc[_ZNK4MMSP4gridILi1EiE6outputEPKc]+0x12e): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi1EiE6outputEPKc[_ZNK4MMSP4gridILi1EiE6outputEPKc]+0x276): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi1EiE6outputEPKc[_ZNK4MMSP4gridILi1EiE6outputEPKc]+0x2dc): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi1EiE6outputEPKc[_ZNK4MMSP4gridILi1EiE6outputEPKc]+0x333): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi1EiE6outputEPKc[_ZNK4MMSP4gridILi1EiE6outputEPKc]+0x3b9): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi1EiE6outputEPKc[_ZNK4MMSP4gridILi1EiE6outputEPKc]+0x52f): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi1EiE6outputEPKc[_ZNK4MMSP4gridILi1EiE6outputEPKc]+0x5ad): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi1EiE6outputEPKc[_ZNK4MMSP4gridILi1EiE6outputEPKc]+0x665): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi1EiE6outputEPKc[_ZNK4MMSP4gridILi1EiE6outputEPKc]+0x151e): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi1EiE6outputEPKc[_ZNK4MMSP4gridILi1EiE6outputEPKc]+0x15fe): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
/tmp/ccYRAxVP.o: In function `MMSP::grid<3, int>::output(char const*) const':
graingrowth.cpp:(.text._ZNK4MMSP4gridILi3EiE6outputEPKc[_ZNK4MMSP4gridILi3EiE6outputEPKc]+0x12f): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi3EiE6outputEPKc[_ZNK4MMSP4gridILi3EiE6outputEPKc]+0x2ad): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi3EiE6outputEPKc[_ZNK4MMSP4gridILi3EiE6outputEPKc]+0x313): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi3EiE6outputEPKc[_ZNK4MMSP4gridILi3EiE6outputEPKc]+0x36a): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi3EiE6outputEPKc[_ZNK4MMSP4gridILi3EiE6outputEPKc]+0x3f0): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi3EiE6outputEPKc[_ZNK4MMSP4gridILi3EiE6outputEPKc]+0x58f): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi3EiE6outputEPKc[_ZNK4MMSP4gridILi3EiE6outputEPKc]+0x60c): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi3EiE6outputEPKc[_ZNK4MMSP4gridILi3EiE6outputEPKc]+0x6c4): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi3EiE6outputEPKc[_ZNK4MMSP4gridILi3EiE6outputEPKc]+0x15cd): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
graingrowth.cpp:(.text._ZNK4MMSP4gridILi3EiE6outputEPKc[_ZNK4MMSP4gridILi3EiE6outputEPKc]+0x16ad): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
/tmp/ccYRAxVP.o: In function `MMSP::grid<3, int>::input(char const*, int, int)':
graingrowth.cpp:(.text._ZN4MMSP4gridILi3EiE5inputEPKcii[_ZN4MMSP4gridILi3EiE5inputEPKcii]+0x62): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)'
collect2: error: ld returned 1 exit status
Makefile:19: recipe for target 'parallel' failed
make: *** [parallel] Error 1
  3 seconds

**Comment by tkphd** [comment]
This looks like a local environment problem, possibly a mismatched glibc version? What version of mpic++ are you using? I'll try getting a working environment with GCC 5 (Debian is slow to update) to test this myself, but it may take some time.

**Comment by amjokisaari** [comment]
No rush...

[amj][~]> ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu3) 2.23

[amj][~]> mpic++ -v
mpicxx for MPICH version 3.2
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/moose/gcc-5.3.0/libexec/gcc/x86_64-unknown-linux-gnu/5.3.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc-5.3.0/configure --prefix=/opt/moose/gcc-5.3.0 --disable-multilib --enable-languages=c,c++,fortran --enable-lto
Thread model: posix
gcc version 5.3.0 (GCC)

**Comment by tkphd** [comment]
OK... using a Ubuntu 16.04 LiveUSB, I've cleared some warnings from gcc 6.3, but the tests successfully build and run in parallel. It looks to me like there are two (or more) MPI environments on your system so that, for example, mpi.h is included from OpenMPI but linked against MPICH. You might look in /etc/alternatives for available mpic++ and mpirun commands, then modify the build_tests.sh to use, for example, mpirun.openmpi instead of generic mpirun.

I'm blaming you, but this error stems from my oversimplified Makefiles, which should be able to consistently choose an appropriate environment from the available options. :man_shrugging:

**Comment by amjokisaari** [comment]
Okay.  My environment definitely is a little spaghetti'd from building different software.  I'll give it a try and report back.

**Comment by amjokisaari** [comment]
Well, that's exciting.  Got it to work by removing anaconda2, looks like it was building with MPICH supplied by the MOOSE module, but trying to run with the MPI version in anaconda2.  And /etc/alternatives --config mpiexec told me I only have one alternative, openMPI that was installed via the package manager.  The tests are now all passing.

**Comment by tkphd** [comment]
Excellent! Glad it's resolved. I'll keep this in mind for make/cmake upgrades down the road.
